<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AntiVandalismAction' => 'herald/AntiVandalismAction.php',
    'AntiVandalismFeedStory' => 'feed/AntiVandalismFeedStory.php',
    'PhabricatorAntiVandalismConfigOptions' => 'config/AntiVandalismConfigOptions.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AntiVandalismAction' => 'HeraldAction',
    'AntiVandalismFeedStory' => 'PhabricatorFeedStory',
    'PhabricatorAntiVandalismConfigOptions' => 'PhabricatorApplicationConfigOptions',
  ),
));
